### ISSUE TITLE
Add support for MySQL

### ISSUE THREAD

**Issue by felippepuhle** [lucasbento/create-graphql#58]
As MySQL user, it would be interesting to have this feature too.

**Comment by sibelius** [comment]
# TODO
- [ ] read mysql table definition
- [ ] add config to .graphqlrc
- [ ] modify type to work with mysql
- [ ] modify loader to work with mysql
- [ ] modify mutation to work with mysql
- [ ] modify connection to work with mysql

I think we should have a generic approach to support any database, maybe a plugin style design

templates generators should receive an array of fields with all information needed

**Comment by sibelius** [comment]
This could help https://github.com/rexxars/sql-to-graphql?

**Comment by lucasbento** [comment]
@sibelius: yeah.

We should start working on #59 asap.

**Comment by sibelius** [comment]
this could help us: https://github.com/gajus/database-types
